### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by basileLeroy** [MohammedAlBay/sass-challenge#1]
# Feedback

## Technical
You didn't completely nest your **index.scss**. (for example, your *articles* are not nested into your *body*)

in your **Red** and **Blue** you are getting the results, nicely done! For readability I would maybe suggest to work a little more like in the example below. Where you import the default styling and simply overwrite certain elements.

```scss
@use 'style';
$txt_color = blue;

body {
    h1,h4,h6 {
        color: $txt_color;
    }
    p {
        color: $txt_color;
    }
}
```

I also recommend to look at naming practices for variables, using a combination of underscores and concatenated words is not ideal, instead go with one or the other.

## Git
Good commit messages and frequent as well. Well done!

On the first day, I see your messages were maybe a bit long, try to stay around 50 characters for a commit message.
